### ISSUE TITLE
License

### ISSUE THREAD

**Issue by trebmuh** [thunderox/stegosaurus-old-version#1]
Hi and thanks for stegosaurus, this is a nice easy-to-use plugin.
It looks to be released under an ISC license if I trust the source.
I suggest to put that in the README.md to make it clearer.
Cheers.

**Comment by thunderox** [comment]
Five years too late but have updated to ISC license. :) Will be adding more features soon now I'm back into programming again.

**Comment by trebmuh** [comment]
Better later than never. Thanks!
