### ISSUE TITLE
Installation directories

### ISSUE THREAD

**Issue by trebmuh** [thunderox/stegosaurus-old-version#4]
It looks like the installation process is putting the preset file in a different directory that the plugin itself: /usr/lib/lv2/stegosaurus.lv2/ and /usr/lib/lv2/stegosaurus-presets.lv2/ (modulate the local/ if choosen). I would suggest to put the presets under stegosaurus.lv2/ (or stegosaurus.lv2/stegosaurus-presets/, or something around this line) in order to help keeping /usr/lib/lv2/ clearer.

**Comment by thunderox** [comment]
Well that is neater just a pity most hosts don't seem to be able to find them lol had to change it back. Will see if there's another way. edit: have worked out how to do this now thanks for the suggestion.
