### ISSUE TITLE
Use MIDI channel 10 instead of 1 (or make it configurable?)

### ISSUE THREAD

**Issue by simonvanderveldt** [thunderox/stegosaurus-old-version#6]
Currently stegosaurus uses MIDI channel 1, which I found out after some digging through the code. Maybe put this in the readme, along with which notes trigger what?
Anyway, drums normally live on MIDI channel 10. Can this be changed?

**Comment by thunderox** [comment]
Yes channel 10 is more standard, I could set that as the default or respond to all channels?

**Comment by simonvanderveldt** [comment]
> Yes channel 10 is more standard, I could set that as the default or respond to all channels?

@thunderox I never responded to this, sorry. I'd say default to 10 and if necessary add an option for the user to override

**Comment by thunderox** [comment]
Finally got around to working on this again, more updates from now on. Stegosaurus now responds only to the default midi drum channel 10.
