### ISSUE TITLE
Add option to allow sounds to play till the end

### ISSUE THREAD

**Issue by simonvanderveldt** [thunderox/stegosaurus-old-version#7]
Currently stegosaurus responds to note-off or 0 velocity note-on messages by stopping playback of that note's sound.
It would be nice if there'd be an option that would allow the sound to always finish playing.
This is best noticed with longer sounds, like the kick sounds from the electro4 preset.

I guess it would be best if this could be done with a separate option per sound (kick, snare, closed hat, open hat).

**Comment by thunderox** [comment]
This was a deliberate design choice because you can get either effect depending on how you set the envelopes. Sorry, my reply took a bit......err long lol I'm going to be around more often from now on.
